eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:9011/eureka/,http://peer-1-server.com:9013/eureka/,http://peer-2-server.com:9014/eureka/
  instance:
    hostname: localhost
    
microservice:
  addcard-service:
    endpoints:
      endpoint:
        uri: http://ADDCARD-SERVICE/addcard/add
  getcard-service:
    endpoints:
      endpoint:
        uri: http://GETCARD-SERVICE/getcard/get
  wallet-gateway:
    endpoints:
      endpoint:
        uri: http://WALLET-GATEWAY/stargate
  tokenizer:
    endpoints:
      endpoint:
        uri: http://localhost:8080/tokenizer/1/tokenmessage
  stargate:
    endpoints:
      endpoint:
        uri: http://localhost:8080/stargate/1/creditmessage
  sg-service:
    endpoints:
      endpoint:
        uri: http://localhost:8080/sgservice/1/sgservice 
