eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9011/eureka/
  instance:
    hostname: localhost
    
microservice:
  service:
    endpoints:
      payment-endpoint: http://PAYMENT-SERVICE/payment-provider/paynow/
      post-endpoint: http://POST-SERVICE/post-service/postdata
