spring:
  profiles: default
server:
  port: 9011
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9011/eureka/
  instance:
    hostname: localhost


spring:
  profiles: peer1
server:
  port: 9012
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9012/eureka/
  instance:
    hostname: localhost
    
    
spring:
  profiles: peer2
server:
  port: 9013
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9013/eureka/
  instance:
    hostname: localhost
