eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer-1-server.com:9012/eureka/,http://peer-2-server.com:9013/eureka/
  instance:
    hostname: localhost
    
microservice:
  addcard-service:
    endpoints:
      endpoint:
        uri: http://ADDCARD-SERVICE/addcard/add
  tokenizer:
    endpoints:
      endpoint:
        uri: http://localhost:8080/tokenizer/1/tokenmessage
  stargate:
    endopints:
      endpoint:
        uri: http://localhost:8080/stargate/1/creditmessage
