eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9011/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment-provider/paynow/
  post-service:
    endpoints:
      endpoint:
        uri: http://POST-SERVICE/post-service/postdata
