eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:9012/eureka/
  instance:
    hostname: localhost
    
microservice:
  addcard-service:
    endpoints:
      endpoint:
        uri: http://ADDCARD-SERVICE/addcard/add
  tokenizer:
    endpoints:
      endpoint:
        uri: http://localhost:8080/tokenizer/1/tokenmessage
  stargate:
    endpoints:
      endpoint:
        uri: http://localhost:8080/stargate/1/creditmessage
